# Generated by Django 5.2.7 on 2026-03-03 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0001_initial"),
        ("training_requests", "0001_initial"),
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingenrollment",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="training_requests.trainingrequest",
            ),
        ),
        migrations.AddField(
            model_name="trainingenrollment",
            name="training_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="trainings.trainingsession",
            ),
        ),
    ]
