# Generated by Django 5.2.11 on 2026-03-08 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_trainingenrollment_certificate_file_and_more'),
        ('training_requests', '0002_alter_trainingrequest_options_and_more'),
        ('trainings', '0002_alter_training_options_alter_trainingsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingenrollment',
            options={'verbose_name': 'Зачисление', 'verbose_name_plural': 'Зачисления'},
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Скан сертификата'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер удостоверения'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='is_attended',
            field=models.BooleanField(default=False, verbose_name='Присутствовал'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='training_requests.trainingrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trainings.trainingsession', verbose_name='Сессия обучения'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingenrollment',
            unique_together={('training_session', 'employee')},
        ),
    ]
