# Generated by Django 5.2.11 on 2026-03-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='supplier_name',
        ),
    ]
