# Generated by Django 5.2.11 on 2026-03-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_requests', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingrequest',
            options={'verbose_name': 'Заявка на обучение', 'verbose_name_plural': 'Заявки на обучение'},
        ),
        migrations.AlterModelOptions(
            name='trainingrequestemployee',
            options={'verbose_name': 'Сотрудник в заявке', 'verbose_name_plural': 'Сотрудники в заявке'},
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_training_requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='trainings.trainingsession', verbose_name='Сессия обучения'),
        ),
        migrations.AlterField(
            model_name='trainingrequestemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_request_participations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='trainingrequestemployee',
            name='training_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='training_requests.trainingrequest', verbose_name='Заявка'),
        ),
    ]
