# Generated by Django 5.2.7 on 2026-03-07 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEMINAR", "Seminar"),
                            ("TRAINING", "Training"),
                            ("CERTIFICATION", "Certification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trainer_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("PER_PERSON", "Per Person"),
                            ("PER_GROUP", "Per Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="trainings.training",
                    ),
                ),
            ],
        ),
    ]
