# Generated by Django 5.2.11 on 2026-03-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_contract_supplier_name'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Обучение', 'verbose_name_plural': 'Обучения'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'verbose_name': 'Сессия обучения', 'verbose_name_plural': 'Сессии обучения'},
        ),
        migrations.AddField(
            model_name='training',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='training',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='training',
            name='pricing_type',
            field=models.CharField(choices=[('PER_PERSON', 'За человека'), ('PER_GROUP', 'За группу')], max_length=20, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer_name',
            field=models.CharField(max_length=255, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.CharField(choices=[('SEMINAR', 'Семинар'), ('TRAINING', 'Тренинг'), ('CERTIFICATION', 'Сертификация')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainings.training', verbose_name='Курс'),
        ),
    ]
