name: Build, Push and Deploy a Docker Image

on:
  push:
    branches: [main, feature/deploy]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_ACCOUNT_EMAIL }}
          password: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/backteam4/api:latest
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
          DB_NAME: "practice_test"
          DB_USER: "django"
          DB_PASSWORD: "django"
          DB_HOST: "localhost"
          DB_PORT: "5432"
          SECRET_KEY: "django-insecure-key-example"
          DEBUG: "True"
          ALLOWED_HOSTS: "*"
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}